
SELECT * FROM products WHERE product_id = 7;

--! CONFIRM THE WHERE STATEMENT IS CORRECT PRIOR TO DELETING
delete from products where product_id =7;
--* DELETE THE RECORDS  **TAKES MORE TIME THAN TRUNCATE** 
-- ! REMOVES RECORDS FROM THE TABLE BUT NOT THE TABLE ITSELF
delete from public."FruitJuice";
--* TRUNCATE THE TABLE **TAKES LESS TIME THAN DELETE**
-- ! REMOVES RECORDS FROM THE TABLE AND THE TABLE ITSELF
truncate public."FruitJuice";
--* DROP THE TABLE   **TAKES THE MOST TIME**
-- ! REMOVES THE TABLE FROM THE DATABASE
drop table public."FruitJuice";






--* DELETE THE RECORDS FROM THE TABLE WALK THROUGH
Select * from orders;
--TODO VIEW DATA TO DELETE AND IDENTIFY FILTER SELECTOR
Select * from orders where order_id=10;
--TODO CONFIRM THE WHERE STATEMENT IS CORRECT PRIOR TO DELETING
Delete from orders where order_id=10;
--TODO DELETE THE RECORDS FROM THE TABLE

--! TO DELETE ALL RECORDS FROM THE ORDERS TABLE
Delete from orders;

